name: githubActions_exercise_workflow
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run linter
        run: npm install && npm run lint

  Cypress_job:
    needs: Linter_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run cypress
        uses: cypress-io/github-action@v2
        id: cypress_step
        if: always()
        with:
          build: npm run build
          start: npm start
      - name: put into result.txt
        shell: bash
        run: echo ${{ steps.cypress_step.outcome }} > result.txt
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result.txt
  
  Add_badge_job:
    needs: Cypress_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: result
      - name: generate output
        id: genoutput
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
      - name: modify readme
        uses: ./.github/actions
        with:
          result: ${{ steps.genoutput.outputs.cypress_outcome }}
      
